language: python
before_install:
  - docker pull ibtfmi/stereotaxyz
  - docker create --name "stereotaxyz" --rm -ti -v "${PWD}":/home/stereotaxyz ibtfmi/stereotaxyz
  - docker start stereotaxyz
  - docker exec stereotaxyz emaint sync -a
  - docker exec stereotaxyz /home/stereotaxyz/.gentoo/install.sh -o
install:
  - docker exec stereotaxyz sh -c 'FEATURES="-test" /home/stereotaxyz/.gentoo/install.sh'
